[workspace]
authors = ["AndreaFrederica <andreafrederica@outlook.com>"]
channels = ["conda-forge"]
name = "TheDisinfectantProject"
platforms = ["win-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.14.2,<3.15"

[pypi-dependencies]
selenium = ">=4.39.0, <5"
webdriver-manager = ">=4.0.2, <5"
pyjson5 = ">=2.0.0, <3"
json5 = ">=0.12.1, <0.13"
