[workspace]
authors = ["AndreaFrederica <andreafrederica@outlook.com>"]
channels = ["conda-forge"]
name = "TheDisinfectantProject"
platforms = ["win-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.13,<3.14"


[pypi-dependencies]
selenium = ">=4.39.0, <5"
webdriver-manager = ">=4.0.2, <5"
pyjson5 = ">=2.0.0, <3"
json5 = ">=0.12.1, <0.13"
beautifulsoup4 = ">=4.12.3, <5"
html5lib = ">=1.1, <2"

paddlepaddle-gpu ={ version = "==3.2.0", index = "https://www.paddlepaddle.org.cn/packages/stable/cu126/"}
paddleocr = { version = ">=3.3.2, <4", extras = ["all"] }
